#!/bin/bash

echo "=== frida-uexplorer Demo ==="
echo ""
echo "This is a demonstration script for frida-uexplorer."
echo "frida-uexplorer is an interactive Unreal Engine memory exploration tool."
echo ""
echo "== Architecture =="
echo "- agent/: Frida JavaScript agent for UE memory operations"
echo "- explorer/: Python client with CLI interface"
echo "- configs/: JSON configuration files for different UE versions"
echo ""
echo "== Usage Examples =="
echo ""
echo "1. Attach to a UE game by process name:"
echo "   python explorer/main.py -n 'YourGame-Win64-Shipping.exe' -c configs/UE4.27.json"
echo ""
echo "2. Attach by PID:"
echo "   python explorer/main.py -p 12345 -c configs/UE5.1.json"
echo ""
echo "3. For Android games:"
echo "   python explorer/main.py -U -f com.epicgames.YourGame -c configs/template.json"
echo ""
echo "== Available Commands =="
echo "- info: Show UE globals (GObjects, GNames, GWorld) information"
echo "- dump <address>: Dump UObject properties at specified address"
echo "- world: Dump the GWorld object"
echo "- find <name>: Search for objects by name"
echo "- findclass <class>: Find objects by class name"
echo "- player: Quick find and dump PlayerController"
echo "- pawn: Quick find and dump Pawn"
echo "- help: Show all commands"
echo ""
echo "== Project Structure =="
ls -la
echo ""
echo "== Configuration Files =="
ls -la configs/
echo ""
echo "== Agent Build =="
echo "Agent compiled successfully: _agent.js"
ls -la _agent.js 2>/dev/null || echo "Build agent with: npm run build"
echo ""
echo "== Requirements =="
echo "- Python 3.x with frida package"
echo "- Target UE game (use in single-player mode!)"
echo ""
echo "== Warning =="
echo "⚠️  Use only for educational purposes and on games you own!"
echo "⚠️  May cause bans if used with anti-cheat protected games!"
echo ""
echo "Happy exploring! 🎮"